DISCORD_WEBHOOK_URL_PREFIX = "https://discord.com/api/webhooks/"

# ENV Variables
DISCORD_LOGGING_HANDLER_WEBHOOK_URL = "DISCORD_LOGGING_HANDLER_WEBHOOK_URL"
DISCORD_LOGGING_HANDLER_WEBHOOK_TOKEN = "DISCORD_LOGGING_HANDLER_WEBHOOK_TOKEN"
DISCORD_LOGGING_HANDLER_WEBHOOK_ID = "DISCORD_LOGGING_HANDLER_WEBHOOK_ID"
